minor update.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -25,7 +25,6 @@ RUN apt-get update -q && apt-get install -y -q --allow-change-held-packages \
     gdb \
     liblog4cxx-dev \
     git \
-    cuda \
     libcudnn8 \
     libcudnn8-dev \
     nvidia-cuda-toolkit \
@@ -36,11 +35,14 @@ RUN apt-get update -q && apt-get install -y -q --allow-change-held-packages \
     && rm -rf /var/lib/apt/lists/* \
 
 # Install Libtorch (example of installation process)
-RUN wget https://download.pytorch.org/libtorch/cu117/libtorch-shared-with-deps-2.0.1%2Bcu117.zip && \
-    unzip libtorch-shared-with-deps-2.0.1+cu117.zip -d /usr/local/ && \
-    ls /usr/local && \
-    ls /usr/local/libtorch && \
-    rm libtorch-shared-with-deps-2.0.1+cu117.zip
+RUN wget -O libtorch.zip https://download.pytorch.org/libtorch/cu117/libtorch-shared-with-deps-2.0.1%2Bcu117.zip && \
+    if [ -f libtorch.zip ]; then \
+        unzip libtorch.zip -d /usr/local/ && \
+        rm libtorch.zip; \
+    else \
+        echo "Libtorch download failed."; \
+        exit 1; \
+    fi
 
 # Verify that Libtorch has been correctly installed (Debugging)
 RUN if [ ! -d "/usr/local/libtorch" ]; then echo "Extraction of Libtorch failed"; exit 1; fi
@@ -48,7 +50,8 @@ RUN if [ ! -d "/usr/local/libtorch" ]; then echo "Extraction of Libtorch failed"
 # Set Libtorch environment variables
 ENV CMAKE_PREFIX_PATH="/usr/local/libtorch/share/cmake/Torch"
 
-# Set up CUDA environment variables
+# Set environment variables for CUDA
+ENV PATH=/usr/local/cuda/bin:$PATH
 ENV CUDACXX=/usr/local/cuda/bin/nvcc
 
 # Configure SSH
