minor update.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -22,11 +22,13 @@ RUN apt-get update && apt-get install -y --allow-change-held-packages \
 # Install Libtorch (example of installation process)
 RUN wget https://download.pytorch.org/libtorch/cu117/libtorch-shared-with-deps-2.0.1%2Bcu117.zip && \
     unzip libtorch-shared-with-deps-2.0.1+cu117.zip -d /usr/local/ && \
-    mv /usr/local/libtorch /usr/local/libtorch && \
+    ls /usr/local && \
+    ls /usr/local/libtorch && \
     rm libtorch-shared-with-deps-2.0.1+cu117.zip
 
+
 # Verify that Libtorch has been correctly installed (Debugging)
-RUN if [ ! -d "/usr/local/libtorch" ]; then echo "Libtorch installation failed"; exit 1; fi
+RUN if [ ! -d "/usr/local/libtorch" ]; then echo "Extraction of Libtorch failed"; exit 1; fi
 
 # Set Libtorch environment variables
 ENV CMAKE_PREFIX_PATH="/usr/local/libtorch/share/cmake/Torch"
